import React from 'react'

import { Inter } from 'next/font/google'

import { Stack } from '@mui/material'
import { NextIntlClientProvider, useMessages } from 'next-intl'

import { ToastContainer } from 'react-toastify'
import type { Metadata } from 'next'

import Providers from '@/utils/Providers'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function PagesLayout({
  children,
  params: { lang }
}: Readonly<{
  children: React.ReactNode
  params: { lang: string }
}>) {
  const messages = useMessages()

  console.log('locale', lang)

  return (
    <html lang={lang} dir={lang === 'ar' ? 'rtl' : 'ltr'}>
      <body className={inter.className}>
        <Providers>
          <NextIntlClientProvider locale={lang} messages={messages}>
            <Stack justifyContent={'center'}>{children}</Stack>
          </NextIntlClientProvider>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  )
}
